### ISSUE TITLE
Missing information.

### ISSUE THREAD

**Issue by VladimirWebDev** [Way2CU/Ono-First-Degree-Site#2]
- [x] Site title
- [x] Behaviour of two links in fixed header. I assumed from name of icons that are used with links that it should be form and share buttons.
![image](https://user-images.githubusercontent.com/25882157/28648420-0906f0a4-726e-11e7-8a6d-73eaae471b81.png)

- [x] Arrow in header ( and footer, mobile version). I added simple animation if it should be different  I'll change.
- [x] Missing two svg icons. Watched right to left, first and second. Speaker and target.
![image](https://user-images.githubusercontent.com/25882157/28635306-69e6d850-723a-11e7-8810-674f22591e76.png)

**Comment by talovdat** [comment]
Site title: תואר ראשון בפרסום ותקשורת שיווקית

Left button opens popup registration fields.
Right button(share) - @MeanEYE Can you apply this button only on the mobile version and when clicking on it, it allows you to share only via Whatsapp? 

Arrow in header- a little animation should do. 

missing two svg icons - do you mean you don't have them in the drive?

**Comment by VladimirWebDev** [comment]
Sprite file doesn't contain those two icons..

**Comment by MeanEYE** [comment]
Nothing can be done about that before sunday.
Make a separate issue, close this one and commit things.
