### ISSUE TITLE
WhatsApp sharing button

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-First-Degree-Site#5]
Create a WhatsApp sharing button on the mobile version.
Place it instead of sharing button (right one).
![image](https://user-images.githubusercontent.com/26923359/28754656-20d77582-7552-11e7-8719-a6efdd94df2f.png)

When clicking, it will share the URL of the mini-site.

**Comment by MeanEYE** [comment]
This is a simple link with WhatsApp URL scheme as [defined here](https://faq.whatsapp.com/en/android/28000012). Client needs to provide us with a message though.

**Comment by talovdat** [comment]
I saw you guys fixed it. 
Closing issue.

**Comment by VladimirWebDev** [comment]
@talovdat  Message was missing.. That's why I didn't close it. If You got it than it is ok.. :) Link is defined at backend so changes are made simple..

**Comment by talovdat** [comment]
Thanks!
